const pokedex = {
  1: {
    name: "Bulbasaur",
    type: ["Grass", "Poison"],
    abilities: ["Overgrow"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png",
  },
  2: {
    name: "Ivysaur",
    type: ["Grass", "Poison"],
    abilities: ["Overgrow"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/002.png"
  },
  3: {
    name: "Venusaur",
    type: ["Grass", "Poison"],
    abilities: ["Overgrow"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/003.png"
  },
  4: {
    name: "Charmander",
    type: ["Fire"],
    abilities: ["Blaze"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png"
  },
  5: {
    name: "Charmeleon",
    type: ["Fire"],
    abilities: ["Blaze"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/005.png"
  },
  6: {
    name: "Charizard",
    type: ["Fire", "Flying"],
    abilities: ["Blaze"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png"
  },
  7: {
    name: "Squirtle",
    type: ["Water"],
    abilities: ["Torrent"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png"
  },
  8: {
    name: "Wartortle",
    type: ["Water"],
    abilities: ["Torrent"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/008.png"
  },
  9: {
    name: "Blastoise",
    type: ["Water"],
    abilities: ["Torrent"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png"
  },
  10: {
    name: "Caterpie",
    type: ["Bug"],
    abilities: ["Shield Dust"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/010.png"
  },
  11: {
    name: "Metapod",
    type: ["Bug"],
    abilities: ["Shed Skin"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/011.png"
  },
  12: {
    name: "Butterfree",
    type: ["Bug", "Flying"],
    abilities: ["Compound Eyes"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/012.png"
  },
  13: {
    name: "Weedle",
    type: ["Bug", "Poison"],
    abilities: ["Shield Dust"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/013.png",
  },
  14: {
    name: "Kakuna",
    type: ["Bug", "Poison"],
    abilities: ["Shed Skin"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/014.png",
  },
  15: {
    name: "Beedrill",
    type: ["Bug", "Poison"],
    abilities: ["Swarm"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/015.png",
  },
  16: {
    name: "Pidgey",
    type: ["Normal", "Flying"],
    abilities: ["Keen Eye"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/016.png",
  },
  17: {
    name: "Pidgeotto",
    type: ["Normal", "Flying"],
    abilities: ["Keen Eye"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/017.png",
  },
  18: {
    name: "Pidgeot",
    type: ["Normal", "Flying"],
    abilities: ["Keen Eye"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/018.png",
  },
  19: {
    name: "Rattata",
    type: ["Normal"],
    abilities: ["Run Away"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/019.png",
  },
  20: {
    name: "Raticate",
    type: ["Normal"],
    abilities: ["Run Away"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/020.png",
  },
  21: {
    name: "Spearow",
    type: ["Normal", "Flying"],
    abilities: ["Keen Eye"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/021.png",
  },
  22: {
    name: "Fearow",
    type: ["Normal", "Flying"],
    abilities: ["Keen Eye"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/022.png",
  },
  23: {
    name: "Ekans",
    type: ["Poison"],
    abilities: ["Intimidate"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/023.png",
  },
  24: {
    name: "Arbok",
    type: ["Poison"],
    abilities: ["Intimidate"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/024.png",
  },
  25: {
    name: "Pikachu",
    type: ["Electric"],
    abilities: ["Static"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png",
  },
  26: {
    name: "Raichu",
    type: ["Electric"],
    abilities: ["Static"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/026.png",
  },
  27: {
    name: "Sandshrew",
    type: ["Ground"],
    abilities: ["Sand Veil"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/027.png",
  },
  28: {
    name: "Sandslash",
    type: ["Ground"],
    abilities: ["Sand Veil"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/028.png",
  },
  29: {
    name: "Nidoran♀",
    type: ["Poison"],
    abilities: ["Poison Point"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/029.png",
  },
  30: {
    name: "Nidorina",
    type: ["Poison"],
    abilities: ["Poison Point"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/030.png",
  },
  31: {
    name: "Nidoqueen",
    type: ["Poison", "Ground"],
    abilities: ["Poison Point"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/031.png",
  },
  32: {
    name: "Nidoran♂",
    type: ["Poison"],
    abilities: ["Poison Point"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/032.png",
  },
  33: {
    name: "Nidorino",
    type: ["Poison"],
    abilities: ["Poison Point"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/033.png",
  },
  34: {
    name: "Nidoking",
    type: ["Poison", "Ground"],
    abilities: ["Poison Point"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/034.png",
  },
  35: {
    name: "Clefairy",
    type: ["Fairy"],
    abilities: ["Cute Charm"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/035.png",
  },
  36: {
    name: "Clefable",
    type: ["Fairy"],
    abilities: ["Cute Charm"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/036.png",
  },
  37: {
    name: "Vulpix",
    type: ["Fire"],
    abilities: ["Flash Fire"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/037.png",
  },
  38: {
    name: "Ninetales",
    type: ["Fire"],
    abilities: ["Flash Fire"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/038.png",
  },
  39: {
    name: "Jigglypuff",
    type: ["Normal", "Fairy"],
    abilities: ["Cute Charm"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/039.png",
  },
  40: {
    name: "Wigglytuff",
    type: ["Normal", "Fairy"],
    abilities: ["Cute Charm"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/040.png",
  },
  41: {
    name: "Zubat",
    type: ["Poison", "Flying"],
    abilities: ["Inner Focus"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/041.png",
  },
  42: {
    name: "Golbat",
    type: ["Poison", "Flying"],
    abilities: ["Inner Focus"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/042.png",
  },
  43: {
    name: "Oddish",
    type: ["Grass", "Poison"],
    abilities: ["Chlorophyll"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/043.png",
  },
  44: {
    name: "Gloom",
    type: ["Grass", "Poison"],
    abilities: ["Chlorophyll"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/044.png",
  },
  45: {
    name: "Vileplume",
    type: ["Grass", "Poison"],
    abilities: ["Chlorophyll"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/045.png",
  },
  46: {
    name: "Paras",
    type: ["Bug", "Grass"],
    abilities: ["Effect Spore"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/046.png",
  },
  47: {
    name: "Parasect",
    type: ["Bug", "Grass"],
    abilities: ["Effect Spore"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/047.png",
  },
  48: {
    name: "Venonat",
    type: ["Bug", "Poison"],
    abilities: ["Compound Eyes"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/048.png",
  },
  49: {
    name: "Venomoth",
    type: ["Bug", "Poison"],
    abilities: ["Shield Dust"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/049.png",
  },
  50: {
    name: "Digglet",
    type: ["Ground"],
    abilities: ["Sand Veil"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/050.png",
  },
  51: {
    name: "Dugtrio",
    type: ["Ground"],
    abilities: ["Sand Veil"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/051.png",
  },
  52: {
    name: "Meowth",
    type: ["Normal"],
    abilities: ["Pickup"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/052.png",
  },
  53: {
    name: "Persian",
    type: ["Normal"],
    abilities: ["Limber"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/053.png",
  },
  54: {
    name: "Psyduck",
    type: ["Water"],
    abilities: ["Damp"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/054.png",
  },
  55: {
    name: "Golduck",
    type: ["Water"],
    abilities: ["Damp"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/055.png",
  },
  56: {
    name: "Mankey",
    type: ["Fighting"],
    abilities: ["Vital Spirit"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/056.png",
  },
  57: {
    name: "Primeape",
    type: ["Fighting"],
    abilities: ["Vital Spirit"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/057.png",
  },
  58: {
    name: "Growlithe",
    type: ["Fire"],
    abilities: ["Intimidate"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/058.png",
  },
  59: {
    name: "Arcanine",
    type: ["Fire"],
    abilities: ["Intimidate"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/059.png",
  },
  60: {
    name: "Poliwag",
    type: ["Water"],
    abilities: ["Water Absorb"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/060.png",
  },
  61: {
    name: "Poliwhirl",
    type: ["Water"],
    abilities: ["Water Absorb"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/061.png",
  },
  62: {
    name: "Poliwrath",
    type: ["Water", "Fighting"],
    abilities: ["Water Absorb"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/062.png",
  },
  63: {
    name: "Abra",
    type: ["Psychic"],
    abilities: ["Synchronize"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/063.png",
  },
  64: {
    name: "Kadabra",
    type: ["Psychic"],
    abilities: ["Synchronize"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/064.png",
  },
  65: {
    name: "Alakazam",
    type: ["Psychic"],
    abilities: ["Synchronize"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/065.png",
  },
  66: {
    name: "Machop",
    type: ["Fighting"],
    abilities: ["Guts"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/066.png",
  },
  67: {
    name: "Machoke",
    type: ["Fighting"],
    abilities: ["Guts"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/067.png",
  },
  68: {
    name: "Machamp",
    type: ["Fighting"],
    abilities: ["Guts"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/068.png",
  },
  69: {
    name: "Bellsprout",
    type: ["Grass", "Poison"],
    abilities: ["Chlorophyll"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/069.png",
  },
  70: {
    name: "Weepinbell",
    type: ["Grass", "Poison"],
    abilities: ["Chlorophyll"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/070.png",
  },
  71: {
    name: "Victreebel",
    type: ["Grass", "Poison"],
    abilities: ["Chlorophyll"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/071.png",
  },
  72: {
    name: "Tentacool",
    type: ["Water", "Poison"],
    abilities: ["Clear Body"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/072.png",
  },
  73: {
    name: "Tentacruel",
    type: ["Water", "Poison"],
    abilities: ["Clear Body"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/073.png",
  },
  74: {
    name: "Geodude",
    type: ["Rock", "Ground"],
    abilities: ["Rock Head"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/074.png",
  },
  75: {
    name: "Graveler",
    type: ["Rock", "Ground"],
    abilities: ["Rock Head"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/075.png",
  },
  76: {
    name: "Golem",
    type: ["Rock", "Ground"],
    abilities: ["Rock Head"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/076.png",
  },
  77: {
    name: "Ponyta",
    type: ["Fire"],
    abilities: ["Run Away"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/077.png",
  },
  78: {
    name: "Rapidash",
    type: ["Fire"],
    abilities: ["Run Away"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/078.png",
  },
  79: {
    name: "Slowpoke",
    type: ["Water", "Psychic"],
    abilities: ["Oblivious"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/079.png",
  },
  80: {
    name: "Slowbro",
    type: ["Water", "Psychic"],
    abilities: ["Oblivious"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/080.png",
  },
  81: {
    name: "Magnemite",
    type: ["Electric", "Steel"],
    abilities: ["Magnet Pull"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/081.png",
  },
  82: {
    name: "Magneton",
    type: ["Electric", "Steel"],
    abilities: ["Magnet Pull"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/082.png",
  },
  83: {
    name: "Farfetch'd",
    type: ["Normal", "Flying"],
    abilities: ["Keen Eye"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/083.png",
  },
  84: {
    name: "Doduo",
    type: ["Normal", "Flying"],
    abilities: ["Run Away"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/084.png",
  },
  85: {
    name: "Dodrio",
    type: ["Normal", "Flying"],
    abilities: ["Run Away"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/085.png",
  },
  86: {
    name: "Seel",
    type: ["Water"],
    abilities: ["Thick Fat"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/086.png",
  },
  87: {
    name: "Dewgong",
    type: ["Water", "Ice"],
    abilities: ["Thick Fat"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/087.png",
  },
  88: {
    name: "Grimer",
    type: ["Poison"],
    abilities: ["Stench"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/088.png",
  },
  89: {
    name: "Muk",
    type: ["Poison"],
    abilities: ["Stench"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/089.png",
  },
  90: {
    name: "Shellder",
    type: ["Water"],
    abilities: ["Shell Armor"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/090.png",
  },
  91: {
    name: "Cloyster",
    type: ["Water", "Ice"],
    abilities: ["Shell Armor"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/091.png",
  },
  92: {
    name: "Gastly",
    type: ["Ghost", "Poison"],
    abilities: ["Levitate"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/092.png",
  },
  93: {
    name: "Haunter",
    type: ["Ghost", "Poison"],
    abilities: ["Levitate"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/093.png",
  },
  94: {
    name: "Gengar",
    type: ["Ghost", "Poison"],
    abilities: ["Levitate"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/094.png",
  },
  95: {
    name: "Onix",
    type: ["Rock", "Ground"],
    abilities: ["Rock Head"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/095.png",
  },
  96: {
    name: "Drowzee",
    type: ["Psychic"],
    abilities: ["Insomnia"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/096.png",
  },
  97: {
    name: "Hypno",
    type: ["Psychic"],
    abilities: ["Insomnia"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/097.png",
  },
  98: {
    name: "Krabby",
    type: ["Water"],
    abilities: ["Hyper Cutter"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/098.png",
  },
  99: {
    name: "Kingler",
    type: ["Water"],
    abilities: ["Hyper Cutter"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/099.png",
  },
  100: {
    name: "Voltorb",
    type: ["Electric"],
    abilities: ["Soundproof"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/100.png",
  },
  101: {
    name: "Electrode",
    type: ["Electric"],
    abilities: ["Soundproof"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/101.png",
  },
  102: {
    name: "Exeggcute",
    type: ["Grass", "Psychic"],
    abilities: ["Chlorophyll"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/102.png",
  },
  103: {
    name: "Exeggutor",
    type: ["Grass", "Psychic"],
    abilities: ["Chlorophyll"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/103.png",
  },
  104: {
    name: "Cubone",
    type: ["Ground"],
    abilities: ["Rock Head"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/104.png",
  },
  105: {
    name: "Marowak",
    type: ["Ground"],
    abilities: ["Rock Head"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/105.png",
  },
  106: {
    name: "Hitmonlee",
    type: ["Fighting"],
    abilities: ["Limber"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/106.png",
  },
  107: {
    name: "Hitmonchan",
    type: ["Fighting"],
    abilities: ["Keen Eye"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/107.png",
  },
  108: {
    name: "Lickitung",
    type: ["Normal"],
    abilities: ["Own Tempo"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/108.png",
  },
  109: {
    name: "Koffing",
    type: ["Poison"],
    abilities: ["Levitate"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/109.png",
  },
  110: {
    name: "Weezing",
    type: ["Poison"],
    abilities: ["Levitate"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/110.png",
  },
  111: {
    name: "Rhyhorn",
    type: ["Ground", "Rock"],
    abilities: ["Lightning Rod"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/111.png",
  },
  112: {
    name: "Rhydon",
    type: ["Ground", "Rock"],
    abilities: ["Lightning Rod"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/112.png",
  },
  113: {
    name: "Chansey",
    type: ["Normal"],
    abilities: ["Natural Cure"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/113.png",
  },
  114: {
    name: "Tangela",
    type: ["Grass"],
    abilities: ["Chlorophyll"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/114.png",
  },
  115: {
    name: "Kangaskhan",
    type: ["Normal"],
    abilities: ["Early Bird"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/115.png",
  },
  116: {
    name: "Horsea",
    type: ["Water"],
    abilities: ["Swift Swim"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/116.png",
  },
  117: {
    name: "Seadra",
    type: ["Water"],
    abilities: ["Poison Point"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/117.png",
  },
  118: {
    name: "Goldeen",
    type: ["Water"],
    abilities: ["Swift Swim"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/118.png",
  },
  119: {
    name: "Seaking",
    type: ["Water"],
    abilities: ["Swift Swim"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/119.png",
  },
  120: {
    name: "Staryu",
    type: ["Water"],
    abilities: ["Illuminate"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/120.png",
  },
  121: {
    name: "Starmie",
    type: ["Water", "Psychic"],
    abilities: ["Illuminate"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/121.png",
  },
  122: {
    name: "Mr. Mime",
    type: ["Psychic", "Fairy"],
    abilities: ["Soundproof"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/122.png",
  },
  123: {
    name: "Scyther",
    type: ["Bug", "Flying"],
    abilities: ["Swarm"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/123.png",
  },
  124: {
    name: "Jynx",
    type: ["Ice", "Psychic"],
    abilities: ["Oblivious"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/124.png",
  },
  125: {
    name: "Electabuzz",
    type: ["Electric"],
    abilities: ["Static"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/125.png",
  },
  126: {
    name: "Magmar",
    type: ["Fire"],
    abilities: ["Flame Body"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/126.png",
  },
  127: {
    name: "Pinsir",
    type: ["Bug"],
    abilities: ["Hyper Cutter"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/127.png",
  },
  128: {
    name: "Tauros",
    type: ["Normal"],
    abilities: ["Intimidate"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/128.png",
  },
  129: {
    name: "Magikarp",
    type: ["Water"],
    abilities: ["Swift Swim"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/129.png",
  },
  130: {
    name: "Gyarados",
    type: ["Water", "Flying"],
    abilities: ["Intimidate"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/130.png",
  },
  131: {
    name: "Lapras",
    type: ["Water", "Ice"],
    abilities: ["Water Absorb"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/131.png",
  },
  132: {
    name: "Ditto",
    type: ["Normal"],
    abilities: ["Limber"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/132.png",
  },
  133: {
    name: "Eevee",
    type: ["Normal"],
    abilities: ["Run Away"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/133.png",
  },
  134: {
    name: "Vaporeon",
    type: ["Water"],
    abilities: ["Water Absorb"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/134.png",
  },
  135: {
    name: "Jolteon",
    type: ["Electric"],
    abilities: ["Volt Absorb"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/135.png",
  },
  136: {
    name: "Flareon",
    type: ["Fire"],
    abilities: ["Flash Fire"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/136.png",
  },
  137: {
    name: "Porygon",
    type: ["Normal"],
    abilities: ["Trace"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/137.png",
  },
  138: {
    name: "Omanyte",
    type: ["Rock", "Water"],
    abilities: ["Swift Swim"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/138.png",
  },
  139: {
    name: "Omastar",
    type: ["Rock", "Water"],
    abilities: ["Swift Swim"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/139.png",
  },
  140: {
    name: "Kabuto",
    type: ["Rock", "Water"],
    abilities: ["Swift Swim"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/140.png",
  },
  141: {
    name: "Kabutops",
    type: ["Rock", "Water"],
    abilities: ["Swift Swim"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/141.png",
  },
  142: {
    name: "Aerodactyl",
    type: ["Rock", "Flying"],
    abilities: ["Rock Head"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/142.png",
  },
  143: {
    name: "Snorlax",
    type: ["Normal"],
    abilities: ["Immunity"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/143.png",
  },
  144: {
    name: "Articuno",
    type: ["Ice", "Flying"],
    abilities: ["Pressure"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/144.png",
  },
  145: {
    name: "Zapdos",
    type: ["Electric", "Flying"],
    abilities: ["Pressure"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/145.png",
  },
  146: {
    name: "Moltres",
    type: ["Fire", "Flying"],
    abilities: ["Pressure"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/146.png",
  },
  147: {
    name: "Dratini",
    type: ["Dragon"],
    abilities: ["Shed Skin"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/147.png",
  },
  148: {
    name: "Dragonair",
    type: ["Dragon"],
    abilities: ["Shed Skin"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/148.png",
  },
  149: {
    name: "Dragonite",
    type: ["Dragon", "Flying"],
    abilities: ["Inner Focus"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/149.png",
  },
  150: {
    name: "Mewtwo",
    type: ["Psychic"],
    abilities: ["Pressure"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/150.png",
  },
  151: {
    name: "Mew",
    type: ["Psychic"],
    abilities: ["Synchronize"],
    image: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/151.png",
  },
};

module.exports = pokedex;
